



# def Outer(func):
#     print("Something is done")
#     def inner(*args, **kwargs):
#         print("Something more is done")

#         return func(*args, **kwargs)

#     return inner
# @Outer
# def remove_i(lst):
#     for i in lst:
#         lst.remove(i)
#     print(lst)

# myTuple = [1,2,3,4,5]
# remove_i(myTuple)

dic = {"A":22, "b":34, "c":12}

dic["b"] = 29
sss = {1,2,3,1,1,0}
l = (1,2,3,1,1,0)
print(sorted(l))